# Lab 10.01 : Convolutional layer - demo

In [1]:
import torch
import torch.nn as nn

C:\Users\raulv\Desktop\1B\Deep Learning from Theory to Practice\Tutorials\dl_course-env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Make a convolutional module
* inputs:  2 channels
* output:  5 activation maps 
* filters are 3x3
* padding with one layer of zero to not shrink anything

In [2]:
mod = nn.Conv2d(2 ,5 ,kernel_size=3, padding=1)

### Make an input 2 x 6 x 6  (two channels, each one has 6 x 6 pixels )

In [3]:
bs=1

x=torch.rand(bs,2,6,6)

print(x)

tensor([[[[0.8471, 0.6476, 0.6904, 0.9712, 0.4126, 0.4620],
          [0.4020, 0.3570, 0.2255, 0.8756, 0.4466, 0.4188],
          [0.6161, 0.4818, 0.9668, 0.0803, 0.4611, 0.8130],
          [0.2545, 0.9373, 0.2942, 0.9677, 0.5841, 0.5157],
          [0.1765, 0.3069, 0.4469, 0.7933, 0.5817, 0.9931],
          [0.8376, 0.3985, 0.8889, 0.3291, 0.8321, 0.1009]],

         [[0.9279, 0.5798, 0.4549, 0.5336, 0.5970, 0.6826],
          [0.3081, 0.9443, 0.3460, 0.3141, 0.0275, 0.2117],
          [0.5998, 0.3227, 0.1292, 0.2842, 0.8287, 0.2495],
          [0.2369, 0.7941, 0.9238, 0.8359, 0.4509, 0.2213],
          [0.2674, 0.6639, 0.5836, 0.5122, 0.9237, 0.1418],
          [0.3687, 0.9822, 0.3228, 0.3069, 0.0040, 0.9915]]]])


### Feed it to the convolutional layer: the output should have 5 channels (each one is 6x6)

In [4]:
y=mod(x)

print(y)

tensor([[[[-0.0506, -0.2536, -0.4021, -0.3256, -0.2780, -0.1789],
          [-0.1333, -0.4153,  0.1135, -0.3317, -0.1789, -0.4026],
          [ 0.0576,  0.2396, -0.5798, -0.4119, -0.4725, -0.4685],
          [ 0.0419, -0.3801, -0.3922, -0.0577, -0.2396, -0.5799],
          [ 0.2865, -0.4441,  0.0174, -0.6197,  0.2390, -0.7129],
          [-0.2228,  0.2938, -0.0703,  0.2038, -0.3120, -0.2936]],

         [[-0.3737, -0.4278, -0.6345, -0.7883, -0.7204, -0.5052],
          [-0.7688, -1.0348, -0.8367, -0.6009, -0.6410, -0.6421],
          [-0.5695, -0.5258, -0.7259, -0.7010, -0.7452, -0.6566],
          [-0.4142, -0.7984, -0.7193, -0.8594, -1.0405, -0.6953],
          [-0.5343, -0.7821, -1.0454, -1.1038, -0.6925, -0.4270],
          [-0.5783, -0.6778, -0.7530, -0.5260, -0.8673, -0.4062]],

         [[-0.3295, -0.1938, -0.4179, -0.2038, -0.1588, -0.0692],
          [-0.4152, -0.2120, -0.4574, -0.5185, -0.2054, -0.1147],
          [-0.4847, -0.4957, -0.4757, -0.3415, -0.2609, -0.1802],
      

### Lets look at the 5 filters.
* Our filters are 2x3x3
* Each of the filter has 2 channels because the inputs have two channels

In [5]:
mod.weight

Parameter containing:
tensor([[[[-0.0750, -0.2190,  0.2065],
          [ 0.1405, -0.1807,  0.2011],
          [-0.1931,  0.1422, -0.1427]],

         [[-0.1082,  0.1734,  0.1714],
          [-0.0007,  0.1006, -0.2219],
          [-0.1974, -0.1603,  0.2185]]],


        [[[-0.0356, -0.0384, -0.2160],
          [-0.0756, -0.1809,  0.0815],
          [-0.1025, -0.2045, -0.2109]],

         [[ 0.0690, -0.2029, -0.0237],
          [-0.0826, -0.1730, -0.1253],
          [-0.0824,  0.1890,  0.1997]]],


        [[[ 0.1881, -0.1920, -0.1587],
          [ 0.0961, -0.0813, -0.2048],
          [-0.0156, -0.0602, -0.2176]],

         [[ 0.0370, -0.0413,  0.1344],
          [-0.0722,  0.1615,  0.1470],
          [ 0.0258,  0.0828, -0.1718]]],


        [[[ 0.2036, -0.1207,  0.0656],
          [ 0.1555,  0.1049,  0.2176],
          [ 0.0875,  0.1026, -0.1861]],

         [[-0.0616, -0.0720, -0.1481],
          [-0.0465,  0.0456, -0.0926],
          [ 0.2231, -0.1378,  0.1709]]],


        [[[ 0.0822